AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  automated-metals-ai-lambda

  Fully automated metals AI analysis with AWS Secrets Manager, S3 storage, and EventBridge scheduling

Parameters:
  TrainingStateMachineArn:
    Type: String
    Default: ""
    Description: Optional Step Functions State Machine ARN used to orchestrate large training jobs

Conditions:
  HasTrainingStateMachineArn: !Not [!Equals [!Ref TrainingStateMachineArn, ""]]

Globals:
  Function:
    Timeout: 300 # 5 minutes for comprehensive analysis
    MemorySize: 1024
  Api:
    Cors:
      AllowMethods: "'OPTIONS,POST'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  # S3 Bucket for storing daily reports
  ReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "metals-ai-reports-v2-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveOldReports
            Status: Enabled
            ExpirationInDays: 2555 # 7 years retention
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER

  # SNS Topic for notifications
  ReportNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "metals-ai-reports-${AWS::AccountId}"
      DisplayName: "Metals AI Daily Reports"

  # Lambda Function
  AutomatedMetalsAIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Environment:
        Variables:
          REPORTS_BUCKET_NAME: !Ref ReportsBucket
          MODELS_BUCKET_NAME: !Ref ReportsBucket
          TRAINING_STATE_MACHINE_ARN: !Ref TrainingStateMachineArn
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref ReportsBucket
        - SecretsManagerReadWrite
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ReportNotificationTopic.TopicName
        - !If
          - HasTrainingStateMachineArn
          - Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref TrainingStateMachineArn
          - !Ref AWS::NoValue
      Events:
        # API Gateway endpoint for manual triggers
        MetalsAIApi:
          Type: Api
          Properties:
            Path: /automated-metals-ai
            Method: post
        # CORS preflight support
        MetalsAIApiOptions:
          Type: Api
          Properties:
            Path: /automated-metals-ai
            Method: options
        # EventBridge scheduled trigger - Daily at 9 AM UTC
        DailyReportSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 9 * * ? *) # 9 AM UTC every day
            Name: DailyGoldReportSchedule
            Description: Daily automated gold market analysis
            Input: >
              {
                "source": "aws.events",
                "operation": "automated_daily_report",
                "metal": "XAU",
                "forecast_days": 7,
                "scheduled": true
              }

  # IAM Role for EventBridge to invoke Lambda
  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt AutomatedMetalsAIFunction.Arn

Outputs:
  AutomatedMetalsAIApi:
    Description: "API Gateway endpoint URL for Automated Metals AI function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/automated-metals-ai/"
    Export:
      Name: !Sub "${AWS::StackName}-AutomatedMetalsAIApi"

  AutomatedMetalsAIFunction:
    Description: "Automated Metals AI Lambda Function ARN"
    Value: !GetAtt AutomatedMetalsAIFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-AutomatedMetalsAIFunction"

  ReportsBucket:
    Description: "S3 Bucket for storing daily reports"
    Value: !Ref ReportsBucket
    Export:
      Name: !Sub "${AWS::StackName}-ReportsBucket"

  DailyScheduleRule:
    Description: "EventBridge rule for daily automated reports"
    Value: !GetAtt AutomatedMetalsAIFunctionDailyReportSchedule.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DailySchedule"

  ReportNotificationTopic:
    Description: "SNS Topic for report notifications"
    Value: !Ref ReportNotificationTopic
    Export:
      Name: !Sub "${AWS::StackName}-NotificationTopic"
